---

  - name: Lets wait for 9091 to be available.
    wait_for: port=9091 delay=5 timeout=15

  - name: Lets wait for 9092 to be available.
    wait_for: port=9092 delay=5 timeout=15

  - name: Creating Topics.
    command: sh "{{ common['soft_link_base_path'] }}"/kafka/bin/kafka-topics.sh --create --zookeeper "{% for host in groups['zookeepernodes'] %}{{ hostvars[host]['inventory_hostname'] }}:2181{% if not loop.last %},{% endif %}{% endfor %}"  --replication-factor 3 --partitions 20 --topic {{ item }}
    sudo: yes
    sudo_user: "{{ kafka_user }}"
    with_items: kafka_topics