# file: roles/jdk/tasks/main.yml

- name: JDK | Oracle JDK | Make sure openjdk is uninstalled
  yum: pkg=openjdk state=absent

- name: JDK | Oracle JDK | Make a directory that holds the Java binaries
  file: path=/usr/local/java state=directory

- name: JDK | Oracle JDK | Copy Oracle JDK
  copy: src=file_archives/{{ jdk_download_filename }} dest=/tmp 

- name: JDK | Oracle JDK | Unpack the compressed JDK binaries
  command: tar -xvzf /tmp/{{ jdk_download_filename }} chdir=/usr/local/java creates=/usr/local/java/{{ jdk_version }}

- name: JDK | Oracle JDK | Update the symbolic link to the JDK install
  file: path={{ java_home }} src=/usr/local/java/{{ jdk_version }} state=link force=yes

- name: JDK | Oracle JDK | Add the JDK binaries to the system path (/etc/profile)
  lineinfile: dest=/etc/profile regexp='^JAVA_HOME={{ java_home }}' line="JAVA_HOME={{ java_home }}" state=present

- name: JDK | Oracle JDK | Add the JDK binaries to the system path (/etc/profile)
  lineinfile: dest=/etc/profile regexp='^PATH=.*JAVA_HOME.*' line="PATH=$PATH:$HOME/bin:$JAVA_HOME/bin" state=present

- name: Remove alternatives before we set them.
  command: rm -f /var/lib/alternatives/{{ item }}
  with_items:
    - java
    - javac
    - javaws
    - javah
    - jar
    - jps

- name: JDK | Oracle JDK | Inform the system where Oracle JDK is located
  alternatives: name={{ item }} link=/usr/bin/{{ item }} path=/usr/local/java/jdk/bin/{{ item }}
  with_items:
    - java
    - javac
    - javaws
    - javah
    - jar
    - jps

